# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutzserver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMFProfile',
        ),
    ]
